/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import CRUDS.Select;
import CRUDS.Update;

/**
 *
 * @author Lucas
 */
public class Alterar extends javax.swing.JDialog {

    /**
     * Creates new form Alterar
     */
    public Alterar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoprodLabel = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        verificarCodigoButton = new javax.swing.JButton();
        quantidadeNovaLabel = new javax.swing.JLabel();
        quantidadeNovaField = new javax.swing.JTextField();
        alterarButton = new javax.swing.JToggleButton();
        cancelarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Quantidade");
        getContentPane().setLayout(new java.awt.GridLayout(7, 1));

        codigoprodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoprodLabel.setText("Codigo do Produto");
        getContentPane().add(codigoprodLabel);

        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(codigoField);

        verificarCodigoButton.setText("Verificar Codigo");
        verificarCodigoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarCodigoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(verificarCodigoButton);

        quantidadeNovaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeNovaLabel.setText("Nova Quantidade");
        getContentPane().add(quantidadeNovaLabel);
        getContentPane().add(quantidadeNovaField);

        alterarButton.setText("Alterar");
        getContentPane().add(alterarButton);

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarCodigoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarCodigoButtonActionPerformed
        if (codigoField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Codigo precisa ser preenchido",
                        "Input Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Integer.parseInt(codigoField.getText());

            } catch (NumberFormatException nfe) {
                System.out.println(nfe);
                JOptionPane.showMessageDialog(this, "Codigo precisa ser inteiro",
                        "Input Error", JOptionPane.WARNING_MESSAGE);
            }
            // Teste com banco de dados
            if(true){
                
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_verificarCodigoButtonActionPerformed

    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoFieldActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alterar dialog = new Alterar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton alterarButton;
    private javax.swing.JToggleButton cancelarButton;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoprodLabel;
    private javax.swing.JTextField quantidadeNovaField;
    private javax.swing.JLabel quantidadeNovaLabel;
    private javax.swing.JButton verificarCodigoButton;
    // End of variables declaration//GEN-END:variables
}
